'use client';

// Phase 10 — Token Intelligence panel.
// Fuses whale holders + recent whale activity + active clusters + AI thesis
// into a right-rail panel on the trading terminal. Mobile: renders as a
// collapsible bottom sheet; desktop: pinned side panel.

import { useEffect, useState } from 'react';
import Link from 'next/link';
import {
  Sparkles, Users, Activity, Network, TrendingUp, TrendingDown, Loader2,
  ChevronDown, ChevronUp, ExternalLink,
} from 'lucide-react';

interface WhaleHolder { address: string; label: string | null; entity_type: string | null; whale_score: number | null; chain: string; last_active_at: string | null }
interface ActivityRow { whale_address: string; action: string; value_usd: number | null; timestamp: string; tx_hash: string; label: string | null }
interface ClusterRow { cluster_id: string; behavior_type: string | null; whale_score: number | null; members: number; community_label: string | null }

interface Brief {
  whale_holders: WhaleHolder[];
  recent_whale_activity: ActivityRow[];
  clusters_touching: ClusterRow[];
  concentration: { top_holder_value: number; whale_count: number; avg_whale_score: number };
  thesis: string | null;
}

function short(a: string): string { return a.length > 14 ? `${a.slice(0, 6)}…${a.slice(-4)}` : a; }
function fmtUsd(v: number | null | undefined): string {
  if (!v || !isFinite(v)) return '—';
  const abs = Math.abs(v);
  if (abs >= 1e9) return `$${(abs / 1e9).toFixed(2)}B`;
  if (abs >= 1e6) return `$${(abs / 1e6).toFixed(2)}M`;
  if (abs >= 1e3) return `$${(abs / 1e3).toFixed(1)}K`;
  return `$${abs.toFixed(0)}`;
}
function timeAgo(iso: string | null): string {
  if (!iso) return '—';
  const diff = (Date.now() - new Date(iso).getTime()) / 1000;
  if (diff < 60) return `${Math.floor(diff)}s`;
  if (diff < 3600) return `${Math.floor(diff / 60)}m`;
  if (diff < 86_400) return `${Math.floor(diff / 3600)}h`;
  return `${Math.floor(diff / 86_400)}d`;
}

export default function TokenIntelligencePanel({
  address, chain, symbol,
}: { address: string; chain: string; symbol: string }) {
  const [brief, setBrief] = useState<Brief | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [open, setOpen] = useState<{ thesis: boolean; whales: boolean; activity: boolean; clusters: boolean }>({
    thesis: true, whales: true, activity: true, clusters: true,
  });

  useEffect(() => {
    let cancelled = false;
    setLoading(true); setError(null);
    fetch(`/api/market/${encodeURIComponent(address)}/intelligence?chain=${chain}`)
      .then((r) => r.json())
      .then((d) => { if (!cancelled) setBrief(d); })
      .catch((e) => { if (!cancelled) setError(String(e?.message || e)); })
      .finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, [address, chain]);

  if (loading) {
    return (
      <div className="p-4 text-slate-500 text-sm flex items-center gap-2">
        <Loader2 className="w-4 h-4 animate-spin" /> Loading intelligence…
      </div>
    );
  }
  if (error) {
    return <div className="p-4 text-red-400 text-xs">{error}</div>;
  }
  if (!brief) return null;

  const totalWhales = brief.whale_holders.length;
  const hasSignal = totalWhales + brief.recent_whale_activity.length + brief.clusters_touching.length > 0;

  return (
    <div className="space-y-3">
      {/* Header */}
      <div className="flex items-center gap-2 px-3 py-2 bg-gradient-to-r from-[#0A1EFF]/10 via-[#7C3AED]/5 to-transparent rounded-lg border border-[#0A1EFF]/30">
        <Sparkles className="w-4 h-4 text-[#8FA3FF]" />
        <div className="flex-1">
          <div className="text-sm font-bold">Token Intelligence</div>
          <div className="text-[10px] text-slate-400">Whale holders · on-chain activity · cluster presence · AI thesis</div>
        </div>
        <span className="text-[9px] px-1.5 py-0.5 rounded bg-emerald-500/15 text-emerald-400 uppercase">Live</span>
      </div>

      {!hasSignal && (
        <div className="p-4 text-center text-xs text-slate-500 bg-white/[0.02] border border-white/10 rounded-lg">
          No tracked whales have traded this token yet. As Naka's whale index grows, signal here will sharpen.
        </div>
      )}

      {/* AI Thesis */}
      {brief.thesis && (
        <Section title="AI Thesis" icon={<Sparkles className="w-3.5 h-3.5" />} open={open.thesis} onToggle={() => setOpen({ ...open, thesis: !open.thesis })}>
          <p className="text-xs text-slate-200 leading-relaxed">{brief.thesis}</p>
          <div className="text-[9px] text-slate-500 mt-1.5">Generated by Naka · not financial advice</div>
        </Section>
      )}

      {/* Concentration stats */}
      {totalWhales > 0 && (
        <div className="grid grid-cols-2 gap-2">
          <Stat label="Tracked whales" value={totalWhales.toLocaleString()} />
          <Stat label="Avg whale score" value={brief.concentration.avg_whale_score ? `${Math.round(brief.concentration.avg_whale_score)}/100` : '—'} />
        </div>
      )}

      {/* Whale holders */}
      {totalWhales > 0 && (
        <Section title={`Whale Holders (${totalWhales})`} icon={<Users className="w-3.5 h-3.5" />} open={open.whales} onToggle={() => setOpen({ ...open, whales: !open.whales })}>
          <div className="max-h-[220px] overflow-y-auto -mx-1">
            {brief.whale_holders.slice(0, 12).map((w) => (
              <div key={w.address} className="flex items-center gap-2 px-2 py-1.5 hover:bg-white/[0.02] rounded">
                <div className="w-1.5 h-1.5 rounded-full bg-emerald-400 shrink-0" />
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-1">
                    <span className="text-xs font-semibold truncate">{w.label || short(w.address)}</span>
                    {w.entity_type && <span className="text-[9px] text-slate-500 uppercase">{w.entity_type}</span>}
                  </div>
                  <div className="text-[10px] text-slate-500 font-mono">{short(w.address)}</div>
                </div>
                <div className="text-right shrink-0">
                  <div className="text-xs font-bold text-[#8FA3FF]">{w.whale_score ?? '—'}</div>
                  <div className="text-[9px] text-slate-500">score</div>
                </div>
              </div>
            ))}
          </div>
        </Section>
      )}

      {/* Recent activity */}
      {brief.recent_whale_activity.length > 0 && (
        <Section title="Recent Whale Activity" icon={<Activity className="w-3.5 h-3.5" />} open={open.activity} onToggle={() => setOpen({ ...open, activity: !open.activity })}>
          <div className="max-h-[240px] overflow-y-auto -mx-1">
            {brief.recent_whale_activity.slice(0, 15).map((a) => {
              const isBuy = /buy|transfer_in|receive/i.test(a.action);
              const isSell = /sell|transfer_out|send/i.test(a.action);
              const Icon = isBuy ? TrendingUp : isSell ? TrendingDown : Activity;
              const tone = isBuy ? 'text-emerald-400' : isSell ? 'text-red-400' : 'text-slate-400';
              return (
                <div key={a.tx_hash} className="flex items-center gap-2 px-2 py-1.5 hover:bg-white/[0.02] rounded">
                  <Icon className={`w-3 h-3 ${tone}`} />
                  <div className="flex-1 min-w-0">
                    <div className="text-[11px] font-semibold truncate">{a.label || short(a.whale_address)}</div>
                    <div className="text-[10px] text-slate-500"><span className={tone}>{a.action}</span> · {fmtUsd(a.value_usd)}</div>
                  </div>
                  <div className="text-[10px] text-slate-500 shrink-0">{timeAgo(a.timestamp)}</div>
                </div>
              );
            })}
          </div>
        </Section>
      )}

      {/* Clusters touching */}
      {brief.clusters_touching.length > 0 && (
        <Section title={`Active Clusters (${brief.clusters_touching.length})`} icon={<Network className="w-3.5 h-3.5" />} open={open.clusters} onToggle={() => setOpen({ ...open, clusters: !open.clusters })}>
          <div className="space-y-1.5">
            {brief.clusters_touching.slice(0, 5).map((c) => (
              <Link
                key={c.cluster_id}
                href={`/dashboard/wallet-clusters/cluster/${c.cluster_id}`}
                className="flex items-center gap-2 px-2 py-2 rounded-lg bg-white/[0.02] hover:bg-white/[0.05] border border-white/5 hover:border-white/10 transition-colors"
              >
                <div className="flex-1 min-w-0">
                  <div className="text-[11px] font-semibold truncate">{c.community_label || c.behavior_type?.replace('_', ' ') || 'Unnamed Cluster'}</div>
                  <div className="text-[10px] text-slate-500">{c.members} members · score {c.whale_score ? Math.round(Number(c.whale_score)) : '—'}</div>
                </div>
                <ExternalLink className="w-3 h-3 text-slate-500" />
              </Link>
            ))}
          </div>
        </Section>
      )}

      {/* VTX handoff */}
      <Link
        href={`/dashboard/vtx-ai?q=${encodeURIComponent(`Deep dive ${symbol} (${address}) on ${chain}. What's the whale sentiment?`)}`}
        className="flex items-center justify-center gap-2 py-2.5 rounded-lg bg-gradient-to-r from-[#0A1EFF] to-[#7C3AED] font-bold text-xs hover:opacity-95"
      >
        <Sparkles className="w-3.5 h-3.5" /> Ask VTX to deep-dive {symbol}
      </Link>
    </div>
  );
}

function Stat({ label, value }: { label: string; value: string }) {
  return (
    <div className="bg-white/[0.02] border border-white/10 rounded-lg p-2">
      <div className="text-[9px] uppercase tracking-wider text-slate-500">{label}</div>
      <div className="text-sm font-bold font-mono">{value}</div>
    </div>
  );
}

function Section({
  title, icon, open, onToggle, children,
}: {
  title: string;
  icon: React.ReactNode;
  open: boolean;
  onToggle: () => void;
  children: React.ReactNode;
}) {
  return (
    <div className="bg-white/[0.02] border border-white/10 rounded-lg overflow-hidden">
      <button onClick={onToggle} className="w-full flex items-center gap-2 px-3 py-2 hover:bg-white/[0.02]">
        <span className="text-slate-400">{icon}</span>
        <span className="text-[11px] font-bold uppercase tracking-wider text-slate-300 flex-1 text-left">{title}</span>
        {open ? <ChevronUp className="w-3.5 h-3.5 text-slate-500" /> : <ChevronDown className="w-3.5 h-3.5 text-slate-500" />}
      </button>
      {open && <div className="px-3 pb-3 pt-1">{children}</div>}
    </div>
  );
}
