"use client";

import { Sparkles, AlertTriangle, TrendingUp } from "lucide-react";
import { AgentAvatar } from "@/components/brand/AgentAvatar";

export interface AlphaReportView {
  summary: string;
  archetype: string;
  strengths: string[];
  risks: string[];
  recent_thesis: string;
  confidence: number;
}

export function AlphaReportCard({ report }: { report: AlphaReportView }) {
  const confPct = Math.round(report.confidence * 100);
  return (
    <div
      className="rounded-2xl border border-blue-500/20 p-5 overflow-hidden relative"
      style={{
        background:
          "radial-gradient(1000px 300px at 0% 0%, rgba(26,58,204,0.14), transparent 50%), linear-gradient(180deg, rgba(12,17,32,0.9), rgba(8,11,22,0.9))",
      }}
    >
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-3">
          <AgentAvatar size={32} />
          <div>
            <h3 className="text-sm font-semibold text-white flex items-center gap-2">
              Alpha Intelligence Report
              <Sparkles size={12} className="text-blue-400" />
            </h3>
            <p className="text-[10px] text-slate-500 mt-0.5 uppercase tracking-wide">Generated by VTX · archetype: {report.archetype}</p>
          </div>
        </div>
        <div className="flex flex-col items-end">
          <span className="text-xs font-mono text-blue-300">{confPct}%</span>
          <span className="text-[9px] uppercase text-slate-600">confidence</span>
        </div>
      </div>

      <p className="text-sm text-slate-200 leading-relaxed mb-4">{report.summary}</p>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mb-4">
        <Panel icon={<TrendingUp size={11} className="text-green-400" />} title="Strengths" items={report.strengths} emptyLabel="No notable strengths detected" tone="up" />
        <Panel icon={<AlertTriangle size={11} className="text-red-400" />} title="Risks" items={report.risks} emptyLabel="No critical risks detected" tone="down" />
      </div>

      <div className="p-3 rounded-xl bg-slate-900/50 border border-slate-800">
        <p className="text-[10px] uppercase tracking-wider text-slate-500 font-semibold mb-1">Current thesis</p>
        <p className="text-xs text-slate-300 leading-relaxed">{report.recent_thesis}</p>
      </div>
    </div>
  );
}

function Panel({
  icon,
  title,
  items,
  emptyLabel,
  tone,
}: {
  icon: React.ReactNode;
  title: string;
  items: string[];
  emptyLabel: string;
  tone: "up" | "down";
}) {
  return (
    <div className="p-3 rounded-xl bg-slate-900/50 border border-slate-800">
      <div className="flex items-center gap-1.5 mb-2">
        {icon}
        <p className="text-[10px] uppercase tracking-wider text-slate-400 font-semibold">{title}</p>
      </div>
      {items.length === 0 ? (
        <p className="text-[11px] text-slate-600 italic">{emptyLabel}</p>
      ) : (
        <ul className="space-y-1">
          {items.map((it, i) => (
            <li key={i} className={`text-xs ${tone === "up" ? "text-green-300" : "text-red-300"} flex items-start gap-1.5`}>
              <span className="text-slate-600">•</span>
              <span>{it}</span>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
