-- Daily Seal — the Oracle's morning briefing.
-- One row per day (PRIMARY KEY on seal_date) generated by the
-- cult-generate-daily-seal cron. Members "break the seal" client-side
-- via the cinematic wax-seal reveal component; the data is read-only on
-- the client side (RLS allows naka_cult members to SELECT, no write).

CREATE TABLE IF NOT EXISTS cult_daily_seals (
  seal_date     date PRIMARY KEY,                           -- one seal per day, UTC
  title         text NOT NULL CHECK (length(title) BETWEEN 6 AND 140),
  body          text NOT NULL CHECK (length(body) BETWEEN 60 AND 4000),
  -- Anthropic gen metadata so we can audit later (model used, token cost).
  model         text NOT NULL DEFAULT 'claude-opus-4-7',
  input_tokens  integer,
  output_tokens integer,
  -- Optional curated context the cron fed Anthropic (top tickers, narratives,
  -- sentiment snapshot). Stored so we can re-ground future seals on the same
  -- inputs if the model output drifts in tone.
  context_json  jsonb,
  generated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS cult_daily_seals_generated_idx
  ON cult_daily_seals (generated_at DESC);

ALTER TABLE cult_daily_seals ENABLE ROW LEVEL SECURITY;

-- Read: any cult member can read the seal.
DROP POLICY IF EXISTS cult_daily_seals_read ON cult_daily_seals;
CREATE POLICY cult_daily_seals_read ON cult_daily_seals
  FOR SELECT USING (
    auth.uid() IS NOT NULL
    AND EXISTS (
      SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.tier = 'naka_cult'
    )
  );

-- Write: server-only via the cron's service-role client. No client INSERT
-- policy on purpose — the seal is generated, not authored by users.
